
/****************API REQUEST TRUCK*************** */

export const FETCH_TRUCK_START = 'FETCH_TRUCK_START';
export const FETCH_TRUCK_SUCCESS = 'FETCH_TRUCK_SUCCESS';
export const FETCH_TRUCK_FAIL = 'FETCH_TRUCK_FAIL';

export const TRUCK_REQUEST_RESET = 'TRUCK_REQUEST_RESET';

export const POST_TRUCK_START = 'POST_TRUCK_START';
export const POST_TRUCK_SUCCESS = 'POST_TRUCK_SUCCESS';
export const POST_TRUCK_FAIL = 'POST_TRUCK_FAIL';

export const PUT_TRUCK_START = 'PUT_TRUCK_START';
export const PUT_TRUCK_SUCCESS = 'PUT_TRUCK_SUCCESS';
export const PUT_TRUCK_FAIL = 'PUT_TRUCK_FAIL';

export const DELTE_TRUCK_START = 'DELTE_TRUCK_START';
export const DELETE_TRUCK_SUCCESS = 'DELETE_TRUCK_SUCCESS';
export const DELTE_TRUCK_FAIL = 'DELTE_TRUCK_FAIL';

/**************************************************** */


/****************API REQUEST SUPPLY*************** */

export const FETCH_SUPPLY_START = 'FETCH_SUPPLY_START';
export const FETCH_SUPPLY_SUCCESS = 'FETCH_SUPPLY_SUCCESS';
export const FETCH_SUPPLY_FAIL = 'FETCH_SUPPLY_FAIL';

export const POST_SUPPLY_START = 'POST_SUPPLY_START';
export const POST_SUPPLY_SUCCESS = 'POST_SUPPLY_SUCCESS';
export const POST_SUPPLY_FAIL = 'POST_SUPPLY_FAIL';

export const PUT_SUPPLY_START = 'PUT_SUPPLY_START';
export const PUT_SUPPLY_SUCCESS = 'PUT_SUPPLY_SUCCESS';
export const PUT_SUPPLY_FAIL = 'PUT_SUPPLY_FAIL';



/**************************************************** */

export const ADD_TRUCK = 'ADD_TRUCK';
export const REMOVE_TRUCK = 'REMOVE_TRUCK';
export const VALUE_CHANGE_TRUCK = 'VALUE_CHANGE_TRUCK';
export const SAVE_TRUCK = 'SAVE_TRUCK';
export const TOGGLE_VIEW_TRUCK = 'TOGGLE_VIEW_TRUCK';

export const ACTIVE_SUPPLY = 'ACTIVE_SUPPLY';
export const ADD_SUPPLY_VALUE = 'ADD_SUPPLY_VALUE';
export const VALUE_CHANGE_SUPPLY = 'VALUE_CHANGE_SUPPLY';
export const ADD_MATERIAL_TO_SUPPLY = 'ADD_MATERIAL_TO_SUPPLY';

export const EDIT_TRUCK_SETTINGS = 'EDIT_TRUCK_SETTINGS';
export const DELETE_TRUCK_SETTINGS = 'DELETE_TRUCK_SETTINGS';

export const EDIT_SUPPLY_SETTINGS = 'EDIT_SUPPLY_SETTINGS';
export const DELETE_SUPPLY_SETTINGS = 'DELETE_SUPPLY_SETTINGS';

export const ACTIVE_ROUTE = 'ACTIVE_ROUTE';

export const ADD_ITEMS_TO_SALES = 'ADD_ITEMS_TO_SALES';
export const TOGGLE_POP_UP = 'SHOW_POP_UP';
export const ON_CHANGE_QUANTITY = 'ON_CHANGE_QUANTITY';
export const SET_TRUCK = 'SET_TRUCK';
export const TOGGLE_FINAL_POP_UP = 'TOGGLE_FINAL_POP_UP';
export const VOID_ITEM = 'VOID_ITEM';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const RESET_POS = 'RESET_POS';
export const EDIT_TRUCK_SEARCH_FORM = 'EDIT_TRUCK_SEARCH_FORM';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const TOGGLE_CUSTOMER_DISPLAY = 'TOGGLE_CUSTOMER_DISPLAY';
export const SET_ACTIVE_ITEM_ROW = 'SET_ACTIVE_ITEM_ROW';
export const EDIT_QUANTITY = 'EDIT_QUANTITY';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CREDIT = 'ADD_CREDIT';

export const TOGGLE_GLOBAL_MODAL = 'TOGGLE_GLOBAL_MODAL';
export const TOGGLE_LOCAL_POPUP_SETTINGS = 'TOGGLE_LOCAL_POPUP_SETTINGS';
