
/****************API REQUEST TRUCK*************** */

export const FETCH_TRUCK_START = 'FETCH_TRUCK_START';
export const FETCH_TRUCK_SUCCESS = 'FETCH_TRUCK_SUCCESS';
export const FETCH_TRUCK_FAIL = 'FETCH_TRUCK_FAIL';

export const TRUCK_REQUEST_RESET = 'TRUCK_REQUEST_RESET';

export const POST_TRUCK_START = 'POST_TRUCK_START';
export const POST_TRUCK_SUCCESS = 'POST_TRUCK_SUCCESS';
export const POST_TRUCK_FAIL = 'POST_TRUCK_FAIL';

export const PUT_TRUCK_START = 'PUT_TRUCK_START';
export const PUT_TRUCK_SUCCESS = 'PUT_TRUCK_SUCCESS';
export const PUT_TRUCK_FAIL = 'PUT_TRUCK_FAIL';

export const DELTE_TRUCK_START = 'DELTE_TRUCK_START';
export const DELETE_TRUCK_SUCCESS = 'DELETE_TRUCK_SUCCESS';
export const DELTE_TRUCK_FAIL = 'DELTE_TRUCK_FAIL';

/**************************************************** */


/****************API REQUEST SUPPLY*************** */

export const FETCH_SUPPLY_START = 'FETCH_SUPPLY_START';
export const FETCH_SUPPLY_SUCCESS = 'FETCH_SUPPLY_SUCCESS';
export const FETCH_SUPPLY_FAIL = 'FETCH_SUPPLY_FAIL';

export const POST_SUPPLY_START = 'POST_SUPPLY_START';
export const POST_SUPPLY_SUCCESS = 'POST_SUPPLY_SUCCESS';
export const POST_SUPPLY_FAIL = 'POST_SUPPLY_FAIL';

export const PUT_SUPPLY_START = 'PUT_SUPPLY_START';
export const PUT_SUPPLY_SUCCESS = 'PUT_SUPPLY_SUCCESS';
export const PUT_SUPPLY_FAIL = 'PUT_SUPPLY_FAIL';

export const DELETE_SUPPLY_START = 'DELETE_SUPPLY_START';
export const DELETE_SUPPLY_SUCCESS = 'DELETE_SUPPLY_SUCCESS';
export const DELETE_SUPPLY_FAIL = 'DELETE_SUPPLY_FAIL';

export const SEARCH_SUPPLY_START = 'SEARCH_SUPPLY_START';
export const SEARCH_SUPPLY_SUCCESS = 'SEARCH_SUPPLY_SUCCESS';
export const SEARCH_SUPPLY_FAIL = 'SEARCH_SUPPLY_FAIL';


/**************************************************** */

/************************API REQUEST CUSTOMER************ */

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';

export const FETCH_CUSTOMER_START = 'FETCH_CUSTOMER_START';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_FAIL = 'FETCH_CUSTOMER_FAIL';

export const POST_CUSTOMER_START = 'POST_CUSTOMER_START';
export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS';
export const POST_CUSTOMER_FAIL = 'POST_CUSTOMER_FAIL';

export const PUT_CUSTOMER_START = 'PUT_CUSTOMER_START';
export const PUT_CUSTOMER_SUCCESS = 'PUT_CUSTOMER_SUCCESS';
export const PUT_CUSTOMER_FAIL = 'PUT_CUSTOMER_FAIL';

export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';

export const SEARCH_CUSTOMER_START = 'SEARCH_CUSTOMER_START';
export const SEARCH_CUSTOMER_SUCCESS = 'SEARCH_CUSTOMER_SUCCESS';
export const SEARCH_CUSTOMER_FAIL = 'SEARCH_CUSTOMER_FAIL';

export const FETCH_CUSTOMER_CREDIT_SUMMARY_START = 'FETCH_CUSTOMER_CREDIT_SUMMARY_START';
export const FETCH_CUSTOMER_CREDIT_SUMMARY_SUCCESS = 'FETCH_CUSTOMER_CREDIT_SUMMARY_SUCCESS';
export const FETCH_CUSTOMER_CREDIT_SUMMARY_FAIL = 'FETCH_CUSTOMER_CREDIT_SUMMARY_FAIL';

/******************************************************** */

/*********************** API REQUEST POS***************** */

export const FETCH_POS_START = 'FETCH_POS_START';
export const FETCH_POS_SUCCESS = 'FETCH_POS_SUCCESS';
export const FETCH_POS_FAIL = 'FETCH_POS_FAIL';

export const FETCH_POS_CUSTOMER_START = 'FETCH_POS_CUSTOMER_START';
export const FETCH_POS_CUSTOMER_SUCCESS = 'FETCH_POS_CUSTOMER_SUCCESS';
export const FETCH_POS_CUSTOMER_FAIL = 'FETCH_POS_CUSTOMER_FAIL';

export const POST_POS_START = 'POST_POS_START';
export const POST_POS_SUCCESS = 'POST_POS_SUCCESS';
export const POST_POS_FAIL = 'POST_POS_FAIL';

/********************************************************* */

/****************************API REQUEST INVOICE********** */

export const SEARCH_INVOICE_START = 'SEARCH_INVOICE_START';
export const SEARCH_INVOICE_SUCCESS = 'SEARCH_INVOICE_SUCCESS';
export const SEARCH_INVOICE_FAIL = 'SEARCH_INVOICE_FAIL';

export const FETCH_INVOICE_START = 'FETCH_INVOICE_START';
export const FETCH_INVOICE_SUCCESS = 'FETCH_INVOICE_SUCCESS';
export const FETCH_INVOICE_FAIL = 'FETCH_INVOICE_FAIL';

export const POST_INVOICE_START = 'POST_INVOICE_START';
export const POST_INVOICE_SUCCESS = 'POST_INVOICE_SUCCESS';
export const POST_INVOICE_FAIL = 'POST_INVOICE_FAIL';

/********************************************************* */

/***********************AUTHENTICATION REQ*****************/

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL'

/********************************************************** */


/**************************************PROFILE REQUEST******** */

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

/********************************************************* */

export const ADD_TRUCK = 'ADD_TRUCK';
export const REMOVE_TRUCK = 'REMOVE_TRUCK';
export const VALUE_CHANGE_TRUCK = 'VALUE_CHANGE_TRUCK';
export const SAVE_TRUCK = 'SAVE_TRUCK';
export const TOGGLE_VIEW_TRUCK = 'TOGGLE_VIEW_TRUCK';

export const ACTIVE_SUPPLY = 'ACTIVE_SUPPLY';
export const ADD_SUPPLY_VALUE = 'ADD_SUPPLY_VALUE';
export const VALUE_CHANGE_SUPPLY = 'VALUE_CHANGE_SUPPLY';
export const ADD_MATERIAL_TO_SUPPLY = 'ADD_MATERIAL_TO_SUPPLY';

export const EDIT_TRUCK_SETTINGS = 'EDIT_TRUCK_SETTINGS';
export const DELETE_TRUCK_SETTINGS = 'DELETE_TRUCK_SETTINGS';

export const EDIT_SUPPLY_SETTINGS = 'EDIT_SUPPLY_SETTINGS';
export const DELETE_SUPPLY_SETTINGS = 'DELETE_SUPPLY_SETTINGS';

export const ACTIVE_ROUTE = 'ACTIVE_ROUTE';

export const ADD_ITEMS_TO_SALES = 'ADD_ITEMS_TO_SALES';
export const TOGGLE_POP_UP = 'SHOW_POP_UP';
export const ON_CHANGE_QUANTITY = 'ON_CHANGE_QUANTITY';
export const SET_TRUCK = 'SET_TRUCK';
export const TOGGLE_FINAL_POP_UP = 'TOGGLE_FINAL_POP_UP';
export const VOID_ITEM = 'VOID_ITEM';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const RESET_POS = 'RESET_POS';
export const EDIT_TRUCK_SEARCH_FORM = 'EDIT_TRUCK_SEARCH_FORM';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const TOGGLE_CUSTOMER_DISPLAY = 'TOGGLE_CUSTOMER_DISPLAY';
export const SET_ACTIVE_ITEM_ROW = 'SET_ACTIVE_ITEM_ROW';
export const EDIT_QUANTITY = 'EDIT_QUANTITY';
export const POPUP_ERROR_TOGGLE = 'POPUP_ERROR_TOGGLE';
export const POPUP_RESPOND_TOGGLE = 'POPUP_RESPOND_TOGGLE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CREDIT = 'ADD_CREDIT';
export const TOGGLE_CUSTOMER_VIEW = 'TOGGLE_CUSTOMER_VIEW';
export const SET_CUSTOMER_SORTING = 'SET_CUSTOMER_SORTING';

export const TOGGLE_GLOBAL_MODAL = 'TOGGLE_GLOBAL_MODAL';
export const TOGGLE_LOCAL_POPUP_SETTINGS = 'TOGGLE_LOCAL_POPUP_SETTINGS';

export const CLEAR_INVOICE_SEARCH = 'CLEAR_INVOICE_SEARCH';

export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';

export const AUTHENTICATE_CHECK = 'AUTHENTICATE_CHECK'
export const CLOSE_AUTH_MESSAGE = 'CLOSE_AUTH_MESSAGE'